####
#### R code for Ushio et al.
#### "Fluctuating interaction network and time-varying stability of a natural fish community"
#### Run all scripts
####

# Run all scripts
# Original results were generated by using rEDM version 0.2.4 and R 3.2.1 on MacOSX.
# We do not recommend running  "00_MaizuruCCM.R" - it may take long (dependsing on the computing environment).
# source("00_MaizuruCCM.R")
source("01_ExtractCausality.R")
source("02_SmapCoef.R")
source("03_Network.R")
source("04_Stability.R")
source("05_StabilityCCM.R")
source("06_StabilitySmap.R")
